import { imageSrc } from "./img/Images";

const list = [
  {
    id: 1,
    category: "project",
    title: "SPC 모니터링 조사",
    desc: "전문면접원이 파리바게트, 던킨 등 전국 모든 매장을 방문하여 제품 및 매장 상태를 점검하고 점검된 정보를 입력 및 데이터 검증, 가공된 정보의 결과물을 제공하는 사이트",
    language: "C#, MSSQL, Javascript, CSS, HTML",
    link: "http://spcbackup.hrcglobal.com",
    images: imageSrc.pj1,
  },
  {
    id: 2,
    category: "project",
    title: "골프매장 유통가격 모니터링 조사",
    desc: "매월 전문면접원이 조사 대상 골프점을 방문하여, 진열된 골프채 종류 및 가격 확인 후 권장가 미만인 매장에 대하여 구매 내역 영수증을 관리하는 사이트",
    language: "C#, MSSQL, Javascript, CSS, HTML",
    link: "http://ssk.hrcglobal.com",
    images: imageSrc.pj2,
  },
  {
    id: 3,
    category: "project",
    title: "순천향대학교 병원 서비스 만족도 조사",
    desc: "순천향대학교 병원에 전화하여 스크립트 내용을 바탕으로 통화 후 해당 정보를 웹 사이트에 기록 및 녹취 파일 업로드를 관리하는 사이트",
    language: "C#, MSSQL, Javascript, CSS, HTML",
    link: "http://schms.hrcglobal.com",
    images: imageSrc.pj3,
  },
  {
    id: 4,
    category: "project",
    title: "삼성판매 모니터링 조사",
    desc: "전국 삼성전자 판매점에 방문하여 제품별 구매 상담 후, 설문 내용 입력 및 경쟁사에 방문 후 제품 및 서비스 응대평가 비교 내용 입력 사이트",
    language: "C#, MSSQL, Javascript, CSS, HTML",
    link: "http://s.sales.hrcglobal.com",
    images: imageSrc.pj4,
  },
  {
    id: 5,
    category: "project",
    title: "홈플러스 가격 모니터링 조사",
    desc: "전문면접원이 매월 홈플러스 매장에 방문하여 할당된 조사 물품에 대한 가격 및 할인 정보에 대한 내용 입력하는 사이트",
    language: "C#, MSSQL, Javascript, CSS, HTML",
    link: "http://ltmm.hrcglobal.com",
    images: imageSrc.pj5,
  },
  {
    id: 6,
    category: "project",
    title: "CAWI 설문조사",
    desc: "",
    language: "",
    link: "",
    images: imageSrc.pj6,
  },
  {
    id: 7,
    category: "react",
    title: "포트폴리오 사이트",
    desc: [
      "Progress Bar lodash throttle 적용",
      "ImageSlider 기능 구현",
      "Modal 기능 구현",
      "Pagenation 기능 구현",
    ],
    language: "React, lodash, styled-components, chart.js",
    link: "https://daeun-react.github.io/portfolio",
    images: imageSrc.portfolio,
  },
  {
    id: 8,
    category: "react",
    title: "Firebase를 이용한 사진 관리 사이트(인스타그램)",
    desc: [
      "Redux-Thunk를 통한 상태관리",
      "Firebase auth/database/storage/hosting 사용",
      "React-hook-form을 사용하여 로그인 기능 구현",
      "이미지 파일 업로드/ 댓글 / 알림 기능 구현",
      "Infinity Scroll 기능 구현",
    ],
    language: "React, Redux-Thunk, Firebase, React-hook-form, ...",
    link: "https://instagram-react-daeun.web.app",
    images: imageSrc.instagram,
  },
  {
    id: 9,
    category: "react",
    title: "Redux-Saga를 통한 메일함 사이트",
    desc: [
      "Redux-saga를 통한 상태관리",
      "사용자 OS에 따른 기본 라이트테마/다크테마 적용",
      "라이트테마/다크테마 토글버튼 구현",
      "메일함 이동 / 메일 삭제 기능 구현",
    ],
    language: "React, Redux, Redux-saga, Axios, Sass, ...",
    link: "https://daeun-react.github.io/mailbox",
    images: imageSrc.mailbox,
  },
  {
    id: 10,
    category: "react",
    title: "웹 성능 최적화 방법 정리하기",
    desc: [
      "로딩 성능 최적화",
      " 이미지 사이즈 최적화/이미지 Preload",
      " Code Split & Component Preload",
      " 텍스트 압축",
      "렌더링 성능 최적화",
      " Bottleneck 성능 최적화",
      " 애니메이션 최적화",
    ],
    language: "",
    link: "https://github.com/daeun-react/performance",
    images: imageSrc.performance,
  },
  {
    id: 11,
    category: "react",
    title: "Themoviedb API를 이용한 영화검색 사이트",
    desc: [
      "https://api.themoviedb.org API 이용",
      "영화 순위 정보 제공(Now Playing, Upcoming Movies, Popular Movies)",
      "TV 프로그램 순위 정보 제공(Top Rated Shows, Popular Shows, Airing Today)",
      "영화 및 TV 프로그램 검색 기능 제공",
    ],
    language: "React, Axios, react-helmet, styled-components",
    link: "https://daeun-react.github.io/moviesite",
    images: imageSrc.movie,
  },
  {
    id: 12,
    category: "react",
    title: "Kakao API를 이용한 Bookstore 사이트",
    desc: [
      "https://dapi.kakao.com/v3/search/book API 이용",
      "useReducer를 통한 상태관리",
      "Infinite Scroll 적용",
      "Lodash Throttle 적용",
    ],
    language: "React, Axios, Sass, uuid",
    link: "https://daeun-react.github.io/bookstore",
    images: imageSrc.book,
  },
  {
    id: 13,
    category: "react",
    title: "Youtube 클론코딩 사이트",
    desc: [
      "MongoDB, Redux, Redux-thunk, Redux-promise를 통한 로그인 상태 관리",
      "Antd 라이브러리 사용",
      "Axios GET/POST를 통한 서버와의 연동",
      "Dropzone, ffmpeg 비디오 업로드 및 썸네일 생성",
      "댓글 및 구독 기능 구현",
    ],
    language: "React, Redux, Antd, Axios, react-dropzone, ffmpeg, ...",
    link: "https://github.com/daeun-react/youtube",
    images: imageSrc.youtube,
  },
  {
    id: 14,
    category: "react",
    title: "ShoppingMall 클론코딩 사이트",
    desc: [
      "Antd 라이브러리 사용",
      "Axios GET/POST를 통한 서버와의 연동",
      "장바구니 담기 기능 구현",
      "Paypal을 통한 결제 기능 구현",
    ],
    language: "React, Redux, Antd, Axios, react-paypal, ...",
    link: "https://github.com/daeun-react/shoppingmall",
    images: imageSrc.shop,
  },
];

export default list;
